### ISSUE TITLE
README setup.cfg typo 

### ISSUE THREAD

**Issue by glenwinters** [asmeurer/pytest-flakes#18]
Under the [Configuring pyflakes options per project and file](https://github.com/fschulze/pytest-flakes#configuring-pyflakes-options-per-project-and-file) section, it mentions "setup.cfg" twice:

"You may configure pyflakes-checking options for your project by adding an flakes-ignore entry to your setup.cfg or setup.cfg file like this:" [Reference](https://github.com/fschulze/pytest-flakes/blame/master/README.rst#L52)

Is it supposed to say "pytest.ini" instead?

**Comment by fschulze** [comment]
Likely yes, I copied that typo from pytest-pep8 on which this plugin was based. There the typo is also still present.

**Comment by hugovk** [comment]
Please see PR https://github.com/asmeurer/pytest-flakes/pull/35.
