### ISSUE TITLE
pytest 3.7.0 regression?

### ISSUE THREAD

**Issue by niksite** [asmeurer/pytest-flakes#23]
Hi,

After upgrading to the 3.7.0 (or 3.7.1) pytest I've got the following CollectError:
```
ERROR at setup of pyflakes-check(ignoring ImportStarUsed UnusedImport) 
...
E           CollectError: ImportError while importing test module '/Users/user/someproject/somefile.py'
...
E               from env import (  # noqa
E           E   ImportError: No module named env
```

Yes, this is a file which supposed to be working only in prod environment and on localhost it will have ImportError. pytest-flakes was working totally fine on this file before updating pytest to 3.7.0.

**Comment by fschulze** [comment]
Could you please try to provide a small complete example? Maybe in a gist?

**Comment by asmeurer** [comment]
Is this still an issue?

**Comment by niksite** [comment]
I believe it's OK now. Sorry for the late response.
